### ISSUE TITLE
Bug: Dashing through walls inside bonus level

### ISSUE THREAD

**Issue by oohdee** [Hodge0699/McompProject#106]
On some occasions, it is possible to dash through a wall inside my scene. We don't know yet if the problem is with the design of the level and the thickness of walls or if the dash code needs a few adjustments.

**Comment by oohdee** [comment]
After the discussion with Nicky, we found out that the issue might be with the player's speed during the dashing. We decided that making those changes will minimalise the possibility of going through walls:

- downing how much player can travel during a dash
- changing the thickness of walls

That seems to fix the issue for now. If it ever comes back during future testing, we will get back to it.

**Comment by 14016036** [comment]
Optimisations and tweaking of the code was also introduced to accommodate Oskars room, as the wall design made me realise I didn’t cater my dash code to every possibility.
