### ISSUE TITLE
Player gets raised into the air when colliding with enemies

### ISSUE THREAD

**Issue by JakeP121** [Hodge0699/McompProject#157]
I think this has something to do with the enemy's position/rotation being frozen but I'm not sure.

**Comment by Nicky-Jones** [comment]
is this still happening? I did freeze their y position so they shouldn't be able to do this. but i think the situation is happens is rare is it not?

**Comment by JakeP121** [comment]
It seems to be every time they collide. Its much more apparent if you keep running at the enemies.

**Comment by Nicky-Jones** [comment]
maybe we can play around with the freezing positions a bit more try to adjust it better

**Comment by JakeP121** [comment]
Solved by unfreezing enemy position
