### ISSUE TITLE
Powerups when player health not 100%

### ISSUE THREAD

**Issue by JakeP121** [Hodge0699/McompProject#171]
I've noticed that after the player has lost at least part of its health the enemies no longer spawn weapon/health drops.

**Comment by Nicky-Jones** [comment]
The way the code works is if the health is less than 20/25% (i forgot the exact value) enemy drops will then only roll off the health drop table, currently as it stands between 50-75/80% there is a 1/4 chance of the health pickup dropping, and once you are below 50% health there is a 50% chance of the health pickup dropping, when originally creating this I used our application of communication to explain the values to the rest of the group so everyone can play test/help balance those values. 

I imagine you probably weren't below 50% health and just got unlucky in the 1/4 drop chance, but for arguments sake I did check and the code is working properly, I did notice however the shooting enemy prefab wasn't updated to drop the health, even tho melee and hybird were (must have been removed or I forgot)

also as part of the health being dropped it was agreed upon by the group that enemies couldn't also drop ammo.
