### ISSUE TITLE
New rewind mechanic implemented (old deprecated)

### ISSUE THREAD

**Issue by LiamVallance** [Hodge0699/McompProject#46]
I have developed a new more flexible and more efficient rewind function that can be attached to any gameobject that we wish to be affected by the rewind. Method of implementation of this mechanic (i.e on keypress or bullet fire etc) still to be decided.

Will be pushing this once Nicky has pushed his boss code to avoid conflicts

**Comment by 14016036** [comment]
closed - completed a while ago. well done!
