### ISSUE TITLE
Reduce room size

### ISSUE THREAD

**Issue by JakeP121** [Hodge0699/McompProject#50]
I think we should reduce the size of each room to force the player to fight more enemies at once and (hopefully) eliminate the need to search for remaining enemies that spawned in the corner of the room which I feel slows down the game. 

The enemy frequency in the room builder adapts to the size of the room so no extra work would have to be done to prevent a current (quite large) room's worth of enemies wouldn't just be crammed into a smaller space.

**Comment by 14016036** [comment]
I like this idea, but i think more balancing will be needed with the frequency of the enemies will be required if we were to make it smaller (maybe half?) would make utilising the time mechanics more prevalent as currently I can complete it all without any of the time mechanics being used.

**Comment by 14016036** [comment]
closed - I believe this was decided and we agreed rooms to be smaller.
