### ISSUE TITLE
Adding a dash?

### ISSUE THREAD

**Issue by JakeP121** [Hodge0699/McompProject#51]
I think implementing a dash could be a cool addition to the game. It would speed up the pace and give the player's an option for when they are hemmed into a corner.

This could simply be a speed boost that lasts a fraction of a second or a roll animation (shouldn't be that hard for a cube but I'm not sure how Unity handles player anims)

**Comment by 14016036** [comment]
if we were to make the rooms smaller I'm not sure this would be a good idea per say, as we'd want players to use the time mechanics moreso than rely on dashing out of tight spots, but I also like the idea and perhaps we could find a good balance with it, especially if we decide on some time mechanics players have a limited time to use it (unless finding a power up) that would make the dash become more important then. 

animations shouldn't be that difficult, I've only used them a few times and probably to a great degree of newbie-ness I was thinking of a forced movement like we currently have when you switch rooms, in the direction that the character is facing, at a high speed and make an animation where the player "looks" invisible" during the transition from one spot to the next, and have it reappear at the end, it'll give it a "teleporting" affect while using code already existing in the game. aka requiring little dev time.

**Comment by 14016036** [comment]
Dash has been added
