### ISSUE TITLE
Boss doesn't rewind on level 2

### ISSUE THREAD

**Issue by JakeP121** [Hodge0699/McompProject#60]
Not sure if it's simply not added or something more sinister but should be looked at.

**Comment by 14016036** [comment]
i think its more sinister..

**Comment by JakeP121** [comment]
I agree, definitely something sinister at work here.

**Comment by LiamVallance** [comment]
This was done for now as there was a problem stopping the boss from shooting while rewinding meaning that the entire time the player (and boss) was rewinding the boss would continue to shoot new bullets at the player and was the player was not in control of the character at the time the player was unable to avoid these bullets meaning that rewinding felt more like an unfair disadvantage. I will continue to look into fixing this problem.

**Comment by LiamVallance** [comment]
I'll get on that as soon as i am home then because i would like to have the boss rewinding too.
