### ISSUE TITLE
New level with Time Travel mechanic

### ISSUE THREAD

**Issue by oohdee** [Hodge0699/McompProject#66]
I'm pretty sure this idea was mentioned during one of the meetings with Mike. It is also very similar to the level "effect and cause" from Titanfall 2. 

So the idea for the new level is quite simple. The main character can now travel back in time to the future to visit Time Tower when it is abandoned and partially destroyed. More details:

- 2 copy of level will be created, one with enemies hunting for the player and one with no enemies but some parts of the level will be cut off or destroyed
- The player will be able to swap between timelines by pressing the button. He will stay in the same spot on the map, just the world around him will be different
- Because "future tower" is in a bad shape player will have to swap between two worlds in order to progress, and at the same time he will be trying not to get killed in the "present tower."
- the level will not use random room generator, it will be predesigned level with simple puzzles (involving swapping between worlds)

Now, my main concern is that it will look different to our standard room design. So I don't know if you guys are ok with this.

**Comment by LiamVallance** [comment]
Personally I quite like the idea of this and would be great to see it in action and we can go from there, even if it ends up not working well with current look and feel of the game it could always stay as a sort of mini game / alternate mode the player could play

**Comment by 14016036** [comment]
closed - This was decided to be a good idea with ohhdee creating it.
