### ISSUE TITLE
UI Graphics

### ISSUE THREAD

**Issue by LiamVallance** [Hodge0699/McompProject#69]
I am currently working on the UI graphics for the game, this will include a full and half heart for the health system, and simple gun pictures to how the user what gun they currently have selected.

Complete so far is the full and half heart as seen below:
![fullheart](https://user-images.githubusercontent.com/10143803/52242757-72bf6d00-28cf-11e9-9398-d31eb86dee36.png)
![hlafheart](https://user-images.githubusercontent.com/10143803/52242758-72bf6d00-28cf-11e9-9af2-76e6a984f7a0.png)

**Comment by LiamVallance** [comment]
Heart has been improved to include an outline in a darker red

**Comment by LiamVallance** [comment]
First weapon graphic has been made, started with Handgun, Shotgun and Machine gun to follow
![handgun](https://user-images.githubusercontent.com/10143803/52306037-9bf30280-298e-11e9-9bf0-c03ece0253a0.png)

**Comment by LiamVallance** [comment]
Shotgun and Assault Rifle (for machine gun) now also complete, this makes all UI graphics originally planned complete so i can now start implementing them into the UI of the game for weapon switching and health tracking:
![ar](https://user-images.githubusercontent.com/10143803/53303515-0cd95c00-3863-11e9-924e-906acafc0690.png)
![shotgun](https://user-images.githubusercontent.com/10143803/53303516-0cd95c00-3863-11e9-93a0-155f6a01b889.png)

**Comment by 14016036** [comment]
Closed - Liam completed this and is currently in the game!
