### ISSUE TITLE
time stop

### ISSUE THREAD

**Issue by Hodge0699** [Hodge0699/McompProject#70]
a basic time stop has been added 

this pauses time but the player is able to move around 

a few things will need to be added to make it 100 complete 
* camera does not follow the character when time is paused
*if the player is within an enemy FOV, when time is paused the enemy will continue to track the player until player out of its FOV range.

**Comment by JakeP121** [comment]
Just had a go of this and noticed the player can also walk through walls, enemies and doors when time is stopped.

**Comment by 14016036** [comment]
that's not good.

**Comment by JakeP121** [comment]
I've fixed the camera issue since I wrote the movement code for it and thought it'd be easier.

**Comment by JakeP121** [comment]
I fixed the collisions bug by making TimeStop manually edit all enemies and bullet's local time rather than global timescale.
