### ISSUE TITLE
Gun powerup overhaul

### ISSUE THREAD

**Issue by JakeP121** [Hodge0699/McompProject#72]
I want to overhaul the whole gun/powerup mechanic to allow the player to hold multiple guns at once similar to how they're used in the Doom games. The guns can then be limited by ammo instead of time which will be replenished by powerups. The player can then switch through their guns using the number keys or bumpers on a controller.

The main reason behind this is that I don't like the feeling of killing the last enemy in a room and having to pick up the powerup and rush to the next room before it runs out. 

I brought this up in the meeting on Monday but since not everyone was I thought I'd post it here to get feedback from the rest of the group.

**Comment by LiamVallance** [comment]
I agree with this i feel it will be a much better system, as i am working on UI graphics for the guns right now as well we could also have it so the user can see all the guns they have on the UI (top or bottom right) but the one they are selected is a more solid colour and larger, this way we could display the ammo count next to each as well so at a glance the user can see how much of each ammo type they have.

**Comment by 14016036** [comment]
Not sure I agree with all the guns, I think the UI might get clogged up especially if someone has a small screen and plays on a smaller reg, I personally prefer the idea of having a rotating switch system where just the one gun icon and the colour that represents that gun in powerup form, it’s clean, it’s simple. And I think it’ll look nice. But I’m open to discussing this more then having a team vote

**Comment by LiamVallance** [comment]
It all comes down to trial and error in the long run so a few idea can be tried out and actually implemented before we fully decide so that we all actually get to see how it looks and feels so i'll start with simplistic so we have it in place and then can start dabbling in more advanced methods and see how they do

**Comment by JakeP121** [comment]
Sounds good. Just merged the mechanic into the master so you can have a look at linking it up with your UI.

**Comment by 14016036** [comment]
Closed - everyone thought this was a good idea and has such been implemented.
